version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # Use the Node.js version compatible with your app
    commands:
      - echo "Installing dependencies"
      - cd client
      - npm install
      - cd ..

  build:
    commands:
      - echo "Building the React app"
      - cd client
      - pwd
      - echo "Path above"
      - echo "Npm version"
      - npm --version
      - echo "Node version"
      - node --version
      - npm run build # Build the React frontend

artifacts:
  files:
    - "**/*"
    - appspec.yml
    - client/appspec.yml
  base-directory: /client/build # The build directory containing the static files
